logLevel: info
api: true
apiAddress: :9997
rtsp: true
rtspAddress: :8554
rtpAddress: :8000
webrtc: true
webrtcAddress: :8889
hls: true
hlsAddress: :8888
playback: false
record: false
paths:
  all_others:
    source: publisher
